import {Platform, StyleSheet} from 'react-native';
import chatColors from './chatColors';
import chatFonts from './chatFonts';

const chatStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: chatColors.white,
  },
  headerContainer: {
    height: Platform.OS === 'android' ? 70 : 70,
    width: '100%',
    flexDirection: 'row',
    backgroundColor: chatColors.white,
    borderBottomColor: chatColors.sky,
    borderBottomWidth: 1,
  },
  headerInnerContainer: {
    flexDirection: 'row',
    height: '100%',
    marginTop: Platform.OS === 'android' ? 6 : 0,
    width: '100%',
  },
  headerMain: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  leftArrowContainer: {
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTxt: {
    color: chatColors.white,
    fontWeight: '500',
    fontSize: 18,
    letterSpacing: 0.75,
    fontFamily: chatFonts.Regular,
  },
  userProfile: {
    height: 48,
    width: 48,
    borderRadius: 48,
    marginStart: 2,
    alignSelf: 'center',
  },
  moreContainer: {
    width: '10%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  recevierContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginVertical: 10,
  },
  recevierInnerContainer: {
    backgroundColor: chatColors.newGrey,
    width: '65%',
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  senderContainer: {
    flexDirection: 'row',
    marginVertical: 15,
    justifyContent: 'flex-end',
    marginHorizontal: 20,
  },
  senderInnerContainer: {
    backgroundColor: chatColors.white,
    width: '65%',
    paddingVertical: 20,
    paddingHorizontal: 20,
    elevation: 4,
    borderRadius: 10,
    shadowOffset: {width: 3, height: 3},
    shadowColor: 'black',
    shadowOpacity: 0.1,
  },
  profileContainer: {
    backgroundColor: chatColors.white,
    width: '65%',
    paddingVertical: 20,
    paddingHorizontal: 20,
    elevation: 4,
    borderRadius: 10,
    shadowOffset: {width: 3, height: 3},
    shadowColor: 'black',
    shadowOpacity: 0.1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  recevierInnerProfileContainer: {
    backgroundColor: chatColors.newGrey,
    width: '65%',
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avoidContainer: {
    flexDirection: 'row',
    height: '10%',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  sendIcon: {
    height: 38,
    width: 42,
    marginRight: 10,
  },
  attachmentIcon: {
    height: 26,
    width: 26,
    marginRight: 10,
  },
  userNameTxt: {
    color: chatColors.black,
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0.75,
    fontFamily: chatFonts.Regular,
    marginStart: 10,
  },
  senderTxt: {
    color: chatColors.black,
    fontWeight: '300',
    fontSize: 13,
    letterSpacing: 0.75,
    fontFamily: chatFonts.Regular,
    lineHeight: 18,
  },
  receiverTxt: {
    fontWeight: '300',
    fontSize: 13,
    letterSpacing: 0.75,
    fontFamily: chatFonts.Regular,
    lineHeight: 18,
    color: chatColors.black,
  },
  blockedTxt: {
    fontWeight: '300',
    fontSize: 13,
    letterSpacing: 0.75,
    fontFamily: chatFonts.Regular,
    lineHeight: 18,
    color: chatColors.black,
    textAlign: 'center',
    fontStyle: 'italic',
  },

  inputContainer: {
    // backgroundColor: chatColors.white,
    // flexDirection: "row",
    // borderRadius: 5,
    // height: 52,
    // alignItems: "center",
    // paddingLeft: 10,
    // flex: 1,
    // marginVertical: 15,
    // borderColor: "#002743",
    // borderWidth: 0.2

    backgroundColor: chatColors.white,
    borderRadius: 5,
    marginHorizontal: 20,
    borderColor: '#002743',
    marginBottom: 20,
    paddingVertical: 8,
    marginTop: 10,
    borderWidth: 0.2,
    flexDirection: 'row',
  },
  blockContainer: {
    backgroundColor: chatColors.white,
    borderRadius: 5,
    borderColor: '#002743',
    marginBottom: 20,
    paddingVertical: 8,
    marginTop: 10,
    borderTopWidth: 0.2,
  },
  inputField: {
    letterSpacing: 0.75,
    color: chatColors.black,
    fontSize: 14,
    flex: 1,
    fontWeight: '400',
    padding: 0,
    paddingStart: 10,
    fontFamily: chatFonts.Regular,
    marginEnd: 10,
  },
});

export default chatStyles;
